Repository stubs
grueneschweiz/weblingservice pull request #12
Opened 2018-11-12 14:53 UTC by cyrillbolliger

With some changes to the MemberMatch class, because php doesn't support enums.

2018-11-13 20:24 UTC, AScheuss approved these changes
Passt gut, danke für die Stubs.

2018-11-13 20:24 UTC, AScheuss commented on app/Repository/Member/MemberRepository.php
> +	 * Find members using a webling query string.
Im Prinzip sollte die Repository doch "agnostisch" gegenüber der Datenbank sein, oder?
Mit einem "Webling"-Query-String würden wir aber schon sehr viel über unsere DB wissen.

**Aber**, das ist derzeit überhaupt kein Problem, da wir für's Erste sowieso nur mit Webling arbeiten, i.e. ich würde es so lassen ;)

2018-11-13 20:24 UTC, AScheuss commented on app/Repository/Group/GroupRepository.php
> +use App\Exceptions\GroupNotFoundException;
Ich nehme an, wir sollten dann alle diese Exceptions fangen und entsprechende Nachrichten an den User schicken/im Log loggen?
(Ein generischer Catch macht ja keinen Sinn, wenn wir es schon so aufdröseln.)

2018-11-13 20:24 UTC, AScheuss commented on app/Repository/Repository.php
> +	protected function api_get( string $endpoint ) {
:thumbsup:

2018-11-13 20:57 UTC, AScheuss requested changes
Ah, Sorry. Habe erst jetzt gesehen, dass die Tests fehlschlagen.
Das hat mit der Umbenennung der Repository-Methoden ("_api") zu tun.

Des Weiteren noch eine Frage:
In https://github.com/grueneschweiz/weblingservice/pull/8#discussion_r231443460 hast du gemeint, ich solle "$memberRepository->get(127)" benutzen. Soll ich den via ein "new MemberRepository" erzeugen (inkl. Base Url von Webling...) oder könnte man das als Konstante erhalten?
(Irgendetwas wie https://sourcemaking.com/design_patterns/creational_patterns - wahrscheinlich "Abstract Factory". - Ich erinnere mich, das mal in einem deiner Codes gesehen zu haben...)

2018-11-14 10:35 UTC, cyrillbolliger commented on app/Repository/Member/MemberRepository.php
> +	 * Find members using a webling query string.
Ja, einen kurzen Moment haben ich überlegt, ob wir das agnostisch implementieren sollen. Doch dann dachte ich an den Aufwand – und entschied mich dagegen 😅

2018-11-14 10:37 UTC, cyrillbolliger commented on app/Repository/Group/GroupRepository.php
> +use App\Exceptions\GroupNotFoundException;
Ich dachte fürs Debugging kann es sehr hilfreich sein, explizite Exceptions zu werfen. Ob wir sie nur loggen wollen und über die API einfach ein 501 zurückgeben wollen, oder ob wir die Exceptions über die API weitergeben wollen, habe ich mir noch nicht überlegt...

2018-11-14 11:04 UTC, cyrillbolliger commented
@AScheuss dito sorry, habe es auch nicht bemerkt mit den Tests. Habe sie soeben gefixt.

Betreffend [#8 (comment)](https://github.com/grueneschweiz/weblingservice/pull/8#discussion_r231443460): Wenn wir uns die Implementierung des Berechtigungssystems sparen wollen, müssen wir den API-Key durchreichen (er muss bereits im request an unsere API enthalten sein). Entsprechen können wir ihn gleich beim Eingang des Requests, diesem den API-Key entnehmen und dem Repository setzen. Oder was meinsch?

2018-11-15 17:45 UTC, merged